steps:
  
  - block: "Request build docker image"

  - label: ":docker: build docker"
    command:
      - "sh .buildkite/build.sh pwa-newdeployment"
    agents:
      - "icube-staging=true"
    
  - block: "deploy staging"

  - label: "Release to staging"
    command:
      - "sh .buildkite/deploy.sh iii-nonprod pwa-newdeployment default"
    agents:
      - "icube-staging=true"
  
#  - block: "Release to production"

#  - label: ":rocket: Deploy iii-prod"
#    command:
#      - "sh .buildkite/deploy.sh iii-prod pwa-newdeployment b2cdemonew"
#    agents:
#      - "iii-prod=true"
